CREATE TABLE store.store
(
    store_id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_staff_id SMALLINT                                                        NOT NULL,
    address_id       INTEGER NOT NULL,
    last_update      TIMESTAMPTZ DEFAULT now()                                       NOT NULL,
    CONSTRAINT unq_manager_staff_id_idx UNIQUE (manager_staff_id)
);
