CREATE TABLE store.customer
(
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id    SMALLINT REFERENCES store.store ON UPDATE CASCADE ON DELETE RESTRICT  NOT NULL,
    first_name  TEXT                                                            NOT NULL,
    last_name   TEXT                                                            NOT NULL,
    email       TEXT,
    address_id  INTEGER NOT NULL,
    activebool  BOOLEAN     DEFAULT true                                        NOT NULL,
    create_date DATE        DEFAULT now()                                       NOT NULL,
    last_update TIMESTAMPTZ DEFAULT now(), -- TODO why it is nullable?
    active      INTEGER
);
