CREATE TABLE store.inventory
(
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id      INTEGER NOT NULL,
    store_id     SMALLINT REFERENCES store.store ON UPDATE CASCADE ON DELETE RESTRICT NOT NULL,
    last_update  TIMESTAMPTZ DEFAULT now()                                      NOT NULL
);

CREATE INDEX ON store.inventory (store_id, film_id);
