CREATE TABLE movies.film
(
    film_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                TEXT                                                              NOT NULL,
    description          TEXT,
    release_year         movies.year,
    language_id          SMALLINT REFERENCES movies.language ON UPDATE CASCADE ON DELETE RESTRICT NOT NULL,
    original_language_id SMALLINT REFERENCES movies.language ON UPDATE CASCADE ON DELETE RESTRICT,
    rental_duration      SMALLINT      DEFAULT 3                                           NOT NULL,
    rental_rate          NUMERIC(4, 2) DEFAULT 4.99                                        NOT NULL,
    length               SMALLINT,
    replacement_cost     NUMERIC(5, 2) DEFAULT 19.99                                       NOT NULL,
    rating               movies.mpaa_rating   DEFAULT 'G',
    special_features     movies.feature[],
    last_update          TIMESTAMPTZ   DEFAULT now()                                       NOT NULL,
    fulltext             TSVECTOR                                                          NOT NULL
);

CREATE TRIGGER film_fulltext_trigger
    BEFORE INSERT OR UPDATE
    ON movies.film
    FOR EACH ROW
EXECUTE PROCEDURE tsvector_update_trigger('fulltext', 'pg_catalog.english', 'title', 'description');

CREATE INDEX ON movies.film (fulltext);
CREATE INDEX ON movies.film (title);
CREATE INDEX ON movies.film (language_id);
CREATE INDEX ON movies.film (original_language_id);
